#!/usr/bin/env python3
"""Generate src/data/worldCupTeams.ts from Guardian WC2026 interactive data."""

from __future__ import annotations

import json
import re
import unicodedata
import urllib.request
from collections import Counter
from pathlib import Path

GUARDIAN_TEAMS_URL = (
    "https://interactive.guim.co.uk/docsdata/1_ZAfmUkTZ4BvDgvhEGaEruakfu4aWIIjjzXaMAiT1yc.json"
)
GUARDIAN_PAGE_URL = (
    "https://www.theguardian.com/football/ng-interactive/2026/jun/04/world-cup-2026-complete-player-guide"
)
ASSET_BASE = (
    "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs"
)
OUT_PATH = Path(__file__).resolve().parents[1] / "src/data/worldCupTeams.ts"

NAME_TO_SLUG: dict[str, str] = {
    "Czechia": "czechia",
    "Mexico": "mexico",
    "South Africa": "south-africa",
    "South Korea": "south-korea",
    "Bosnia and Herzegovina": "bosnia-and-herzegovina",
    "Canada": "canada",
    "Qatar": "qatar",
    "Switzerland": "switzerland",
    "Brazil": "brazil",
    "Haiti": "haiti",
    "Morocco": "morocco",
    "Scotland": "scotland",
    "Australia": "australia",
    "Paraguay": "paraguay",
    "Turkey": "turkey",
    "USA": "usa",
    "Curaçao": "curacao",
    "Ecuador": "ecuador",
    "Germany": "germany",
    "Côte d'Ivoire": "cote-d-ivoire",
    "Japan": "japan",
    "Netherlands": "netherlands",
    "Sweden": "sweden",
    "Tunisia": "tunisia",
    "Belgium": "belgium",
    "Egypt": "egypt",
    "Iran": "iran",
    "New Zealand": "new-zealand",
    "Cape Verde": "cape-verde",
    "Saudi Arabia": "saudi-arabia",
    "Spain": "spain",
    "Uruguay": "uruguay",
    "France": "france",
    "Iraq": "iraq",
    "Norway": "norway",
    "Senegal": "senegal",
    "Algeria": "algeria",
    "Argentina": "argentina",
    "Austria": "austria",
    "Jordan": "jordan",
    "Colombia": "colombia",
    "DR Congo": "dr-congo",
    "Portugal": "portugal",
    "Uzbekistan": "uzbekistan",
    "Croatia": "croatia",
    "England": "england",
    "Ghana": "ghana",
    "Panama": "panama",
}


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req) as res:
        return res.read().decode("utf-8", "ignore")


def parse_home_colours(html: str) -> dict[str, str]:
    pattern = (
        r"\.gv-([a-z0-9_-]+) \.gv-team-base-background\{background-color:(#[0-9a-fA-F]{3,6})\}"
    )
    return {m.group(1): m.group(2) for m in re.finditer(pattern, html)}


def hex_to_rgb(hex_colour: str) -> tuple[int, int, int]:
    h = hex_colour.lstrip("#")
    if len(h) == 3:
        h = "".join(ch * 2 for ch in h)
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def rgb_to_hex(rgb: tuple[int, int, int]) -> str:
    return f"#{rgb[0]:02x}{rgb[1]:02x}{rgb[2]:02x}"


def colour_distance(a: tuple[int, int, int], b: tuple[int, int, int]) -> float:
    return sum((x - y) ** 2 for x, y in zip(a, b)) ** 0.5


def away_colour_from_kit(slug: str, home_hex: str) -> str:
    from PIL import Image

    url = f"{ASSET_BASE}/kits/{slug}_kit_away.png"
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req) as res:
        img = Image.open(res).convert("RGBA")

    home_rgb = hex_to_rgb(home_hex)
    pixels = [px[:3] for px in img.getdata() if px[3] > 180]
    counts = Counter(pixels)

    for rgb, _ in counts.most_common(30):
        if colour_distance(rgb, home_rgb) > 55:
            return rgb_to_hex(rgb)

    for rgb, _ in counts.most_common(10):
        luminance = 0.299 * rgb[0] + 0.587 * rgb[1] + 0.114 * rgb[2]
        if luminance > 200 or luminance < 45:
            return rgb_to_hex(rgb)

    return "#ffffff" if sum(hex_to_rgb(home_hex)) < 380 else "#121212"


def main() -> None:
    teams_json = json.loads(fetch(GUARDIAN_TEAMS_URL))
    home_colours = parse_home_colours(fetch(GUARDIAN_PAGE_URL))

    rows: list[dict[str, str]] = []
    for team in teams_json["sheets"]["Teams"]:
        name = team["Team"]
        slug = NAME_TO_SLUG[name]
        home = home_colours[slug]
        away = away_colour_from_kit(slug, home)
        rows.append(
            {
                "name": name,
                "slug": slug,
                "group": team["Group"],
                "homeKit": home,
                "awayKit": away,
                "crest": f"{ASSET_BASE}/crests/{slug}_badge.png",
            }
        )

    rows.sort(key=lambda r: (r["group"], r["name"]))

    lines = [
        "/** Generated by scripts/generate-world-cup-teams.py — do not edit by hand. */",
        "",
        "export interface WorldCupTeam {",
        "  name: string",
        "  slug: string",
        "  group: string",
        "  homeKit: string",
        "  awayKit: string",
        "  crest: string",
        "}",
        "",
        "export const worldCupTeams: WorldCupTeam[] = " + json.dumps(rows, indent=2),
        "",
    ]
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(rows)} teams to {OUT_PATH}")


if __name__ == "__main__":
    main()
