/** Generated by scripts/generate-world-cup-teams.py — do not edit by hand. */

export interface WorldCupTeam {
  name: string
  slug: string
  group: string
  homeKit: string
  awayKit: string
  crest: string
}

export const worldCupTeams: WorldCupTeam[] = [
  {
    "name": "Czechia",
    "slug": "czechia",
    "group": "A",
    "homeKit": "#b1383e",
    "awayKit": "#000000",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/czechia_badge.png"
  },
  {
    "name": "Mexico",
    "slug": "mexico",
    "group": "A",
    "homeKit": "#4fa487",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/mexico_badge.png"
  },
  {
    "name": "South Africa",
    "slug": "south-africa",
    "group": "A",
    "homeKit": "#198971",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/south-africa_badge.png"
  },
  {
    "name": "South Korea",
    "slug": "south-korea",
    "group": "A",
    "homeKit": "#d53933",
    "awayKit": "#9d76b4",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/south-korea_badge.png"
  },
  {
    "name": "Bosnia and Herzegovina",
    "slug": "bosnia-and-herzegovina",
    "group": "B",
    "homeKit": "#124b96",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/bosnia-and-herzegovina_badge.png"
  },
  {
    "name": "Canada",
    "slug": "canada",
    "group": "B",
    "homeKit": "#d53933",
    "awayKit": "#191b1a",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/canada_badge.png"
  },
  {
    "name": "Qatar",
    "slug": "qatar",
    "group": "B",
    "homeKit": "#a3434a",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/qatar_badge.png"
  },
  {
    "name": "Switzerland",
    "slug": "switzerland",
    "group": "B",
    "homeKit": "#d73b3b",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/switzerland_badge.png"
  },
  {
    "name": "Brazil",
    "slug": "brazil",
    "group": "C",
    "homeKit": "#cea724",
    "awayKit": "#040707",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/brazil_badge.png"
  },
  {
    "name": "Haiti",
    "slug": "haiti",
    "group": "C",
    "homeKit": "#2b4d99",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/haiti_badge.png"
  },
  {
    "name": "Morocco",
    "slug": "morocco",
    "group": "C",
    "homeKit": "#b1383e",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/morocco_badge.png"
  },
  {
    "name": "Scotland",
    "slug": "scotland",
    "group": "C",
    "homeKit": "#3472b7",
    "awayKit": "#e5786e",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/scotland_badge.png"
  },
  {
    "name": "Australia",
    "slug": "australia",
    "group": "D",
    "homeKit": "#eaa238",
    "awayKit": "#135e75",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/australia_badge.png"
  },
  {
    "name": "Paraguay",
    "slug": "paraguay",
    "group": "D",
    "homeKit": "#d42e27",
    "awayKit": "#20212c",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/paraguay_badge.png"
  },
  {
    "name": "Turkey",
    "slug": "turkey",
    "group": "D",
    "homeKit": "#e22c33",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/turkey_badge.png"
  },
  {
    "name": "USA",
    "slug": "usa",
    "group": "D",
    "homeKit": "#eb2227",
    "awayKit": "#040707",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/usa_badge.png"
  },
  {
    "name": "Cura\u00e7ao",
    "slug": "curacao",
    "group": "E",
    "homeKit": "#284e8f",
    "awayKit": "#f5e084",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/curacao_badge.png"
  },
  {
    "name": "C\u00f4te d'Ivoire",
    "slug": "cote-d-ivoire",
    "group": "E",
    "homeKit": "#e87324",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/cote-d-ivoire_badge.png"
  },
  {
    "name": "Ecuador",
    "slug": "ecuador",
    "group": "E",
    "homeKit": "#cea724",
    "awayKit": "#21283f",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/ecuador_badge.png"
  },
  {
    "name": "Germany",
    "slug": "germany",
    "group": "E",
    "homeKit": "#f39b1f",
    "awayKit": "#142b4b",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/germany_badge.png"
  },
  {
    "name": "Japan",
    "slug": "japan",
    "group": "F",
    "homeKit": "#283a85",
    "awayKit": "#f4f8eb",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/japan_badge.png"
  },
  {
    "name": "Netherlands",
    "slug": "netherlands",
    "group": "F",
    "homeKit": "#e87457",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/netherlands_badge.png"
  },
  {
    "name": "Sweden",
    "slug": "sweden",
    "group": "F",
    "homeKit": "#cea724",
    "awayKit": "#15489b",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/sweden_badge.png"
  },
  {
    "name": "Tunisia",
    "slug": "tunisia",
    "group": "F",
    "homeKit": "#c33733",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/tunisia_badge.png"
  },
  {
    "name": "Belgium",
    "slug": "belgium",
    "group": "G",
    "homeKit": "#c02026",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/belgium_badge.png"
  },
  {
    "name": "Egypt",
    "slug": "egypt",
    "group": "G",
    "homeKit": "#c33733",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/egypt_badge.png"
  },
  {
    "name": "Iran",
    "slug": "iran",
    "group": "G",
    "homeKit": "#c33733",
    "awayKit": "#000000",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/iran_badge.png"
  },
  {
    "name": "New Zealand",
    "slug": "new-zealand",
    "group": "G",
    "homeKit": "#0a2569",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/new-zealand_badge.png"
  },
  {
    "name": "Cape Verde",
    "slug": "cape-verde",
    "group": "H",
    "homeKit": "#124b96",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/cape-verde_badge.png"
  },
  {
    "name": "Saudi Arabia",
    "slug": "saudi-arabia",
    "group": "H",
    "homeKit": "#106d39",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/saudi-arabia_badge.png"
  },
  {
    "name": "Spain",
    "slug": "spain",
    "group": "H",
    "homeKit": "#c23531",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/spain_badge.png"
  },
  {
    "name": "Uruguay",
    "slug": "uruguay",
    "group": "H",
    "homeKit": "#88bce5",
    "awayKit": "#232a3c",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/uruguay_badge.png"
  },
  {
    "name": "France",
    "slug": "france",
    "group": "I",
    "homeKit": "#2b3187",
    "awayKit": "#cfe6e1",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/france_badge.png"
  },
  {
    "name": "Iraq",
    "slug": "iraq",
    "group": "I",
    "homeKit": "#317a67",
    "awayKit": "#000000",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/iraq_badge.png"
  },
  {
    "name": "Norway",
    "slug": "norway",
    "group": "I",
    "homeKit": "#d6383d",
    "awayKit": "#040707",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/norway_badge.png"
  },
  {
    "name": "Senegal",
    "slug": "senegal",
    "group": "I",
    "homeKit": "#317a67",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/senegal_badge.png"
  },
  {
    "name": "Algeria",
    "slug": "algeria",
    "group": "J",
    "homeKit": "#19967a",
    "awayKit": "#000000",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/algeria_badge.png"
  },
  {
    "name": "Argentina",
    "slug": "argentina",
    "group": "J",
    "homeKit": "#75abdc",
    "awayKit": "#061e39",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/argentina_badge.png"
  },
  {
    "name": "Austria",
    "slug": "austria",
    "group": "J",
    "homeKit": "#cd3733",
    "awayKit": "#1f565e",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/austria_badge.png"
  },
  {
    "name": "Jordan",
    "slug": "jordan",
    "group": "J",
    "homeKit": "#b1383e",
    "awayKit": "#000000",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/jordan_badge.png"
  },
  {
    "name": "Colombia",
    "slug": "colombia",
    "group": "K",
    "homeKit": "#cea724",
    "awayKit": "#0f365c",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/colombia_badge.png"
  },
  {
    "name": "DR Congo",
    "slug": "dr-congo",
    "group": "K",
    "homeKit": "#c33733",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/dr-congo_badge.png"
  },
  {
    "name": "Portugal",
    "slug": "portugal",
    "group": "K",
    "homeKit": "#d82227",
    "awayKit": "#fbfaf8",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/portugal_badge.png"
  },
  {
    "name": "Uzbekistan",
    "slug": "uzbekistan",
    "group": "K",
    "homeKit": "#124b96",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/uzbekistan_badge.png"
  },
  {
    "name": "Croatia",
    "slug": "croatia",
    "group": "L",
    "homeKit": "#1268b3",
    "awayKit": "#161a4c",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/croatia_badge.png"
  },
  {
    "name": "England",
    "slug": "england",
    "group": "L",
    "homeKit": "#c73631",
    "awayKit": "#1c2a58",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/england_badge.png"
  },
  {
    "name": "Ghana",
    "slug": "ghana",
    "group": "L",
    "homeKit": "#cea724",
    "awayKit": "#fae066",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/ghana_badge.png"
  },
  {
    "name": "Panama",
    "slug": "panama",
    "group": "L",
    "homeKit": "#d33832",
    "awayKit": "#ffffff",
    "crest": "https://interactive.guim.co.uk/atoms/2026/04/world-cup-player-guide-2026/assets/v/1780676707960/imgs/crests/panama_badge.png"
  }
]
